//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMLyThuyet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietBaoTri
    {
        public int STT { get; set; }
        public string MaNV { get; set; }
        public string MaTB { get; set; }
        public Nullable<System.DateTime> NgayBaoTri { get; set; }
        public Nullable<int> ChiPhi { get; set; }
    
        public virtual NhanVien NhanVien { get; set; }
        public virtual ThietBi ThietBi { get; set; }
    }
}
