//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMLyThuyet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        public string MaHD { get; set; }
        public System.DateTime NgayThanhToan { get; set; }
        public string MaMB { get; set; }
        public string MaNV { get; set; }
        public Nullable<int> TongTien { get; set; }
    
        public virtual MatBang MatBang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
    }
}
