//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMLyThuyet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class KhachHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KhachHang()
        {
            this.MatBangs = new HashSet<MatBang>();
        }
    
        public string MaKH { get; set; }
        public string HoVaTen { get; set; }
        public string DiaCHi { get; set; }
        public System.DateTime NgaySinh { get; set; }
        public System.DateTime NgayGiaNhap { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public Nullable<int> IDUSER { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatBang> MatBangs { get; set; }
        public virtual User User { get; set; }
    }
}
