//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CNPMLyThuyet.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MatBang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MatBang()
        {
            this.HoaDons = new HashSet<HoaDon>();
            this.DoanhThus = new HashSet<DoanhThu>();
        }
    
        public string MaMB { get; set; }
        public string TenMB { get; set; }
        public string TinhTrang { get; set; }
        public int GiaTien { get; set; }
        public string MaTang { get; set; }
        public string MaKH { get; set; }
        public string ImagePath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HoaDon> HoaDons { get; set; }
        public virtual KhachHang KhachHang { get; set; }
        public virtual Tang Tang { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DoanhThu> DoanhThus { get; set; }
    }
}
